### ISSUE TITLE
Piccoli consigli

### ISSUE THREAD

**Issue by gbvitrano** [giuragu/regolamento-bilancio-democrazia-partecipata-sangiuseppejato#7]
## Blocco Configuration 

Aggiungere la favicon

Nel blocco  `## Configuration` del file mkdocs.yml aggiungere il codice per fare caricare la favicon, l'icona che viene visualizzata nella linguetta della pagina dei vari browser. 
Basta aggiungere questo codice e caricare il file favicon dentro la cartella images

`favicon: images/favicon.ico` 

[favicon.zip](https://github.com/giuragu/regolamento-bilancio-democrazia-partecipata-sangiuseppejato/files/7379375/favicon.zip)

## Blocco Social Media
Aggiungere la descrizione alle icone social del footer (tooltip al passaggio del mouse)
```
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/giuragu/regolamento-bilancio-democrazia-partecipata-sangiuseppejato
      name: Repository Github
    - icon: fontawesome/solid/envelope
      link: mailto:comunesangiuseppejato@pec.it
      name: Posta Certificata Comune San Giuseppe Jato
    - icon: fontawesome/solid/book
      link: https://readthedocs.org/projects/regolamento-bilancio-democrazia-partecipata-sangiuseppejato
      name: Progetto Read the docs
```

Ps... il valore del campo `name` lo puoi modificare 

##  Bloco copiright

Aggiungere link alla licenza

```
copyright: <a href="https://www.comune.sangiuseppejato.pa.it/" title="Comune di San Giuseppe Jato " target="_blank"> Comune di San Giuseppe Jato </a> | <a href="https://creativecommons.org/licenses/by/4.0/deed.it" title="Attribuzione 4.0 Internazionale (CC BY 4.0)" target="_blank"> CC BY 4.0 Int Licence</a>
```
